stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "20"

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run lint --if-present
    - npm test --if-present
  only:
    - branches

build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main
    - master
    - develop

deploy:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - echo "Add your deployment steps here"
    # Add your deployment commands
  only:
    - main
    - master
  when: manual
